/**
 * Build for el-coso-3000.
 *
 * Produces a single file: `dist/placeholder.html`, which opens with a double
 * click from Finder, without a server or an internet connection.
 *
 * Steps:
 *   1. Regenerates `src/core/font-data.ts` from the woff2 in `fonts/`.
 *   2. Bundles `src/main.ts` with Bun's bundler in IIFE format.
 *   3. Injects the JS and CSS into `src/index.html`.
 *   4. Verifies that the result loads nothing from the network.
 *
 * Run: `bun run build`
 */
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT = join(root, 'fonts/Montserrat-SemiBold-latin.woff2');
const FONT_DATA = join(root, 'src/core/font-data.ts');
const ENTRY = join(root, 'src/main.ts');
const TEMPLATE = join(root, 'src/index.html');
const STYLES = join(root, 'src/styles.css');
const OUT_DIR = join(root, 'dist');
const OUT = join(OUT_DIR, 'placeholder.html');

const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;

// ── 1. Embedded font ────────────────────────────────────────────────

async function bakeFont(): Promise<number> {
  const bytes = new Uint8Array(await Bun.file(FONT).arrayBuffer());
  // A woff2 signature is 'wOF2'. If it's missing, the file was downloaded
  // incorrectly, and we need to know now rather than when fallback text appears.
  const signature = new TextDecoder().decode(bytes.slice(0, 4));
  if (signature !== 'wOF2') {
    throw new Error(`"${FONT}" is not a valid woff2 (signature "${signature}"). Run \`bun run fetch:font\`.`);
  }
  const b64 = Buffer.from(bytes).toString('base64');
  const header = [
    '/* Generated by scripts/build.ts. Do not edit by hand. */',
    '/* Font: fonts/Montserrat-SemiBold-latin.woff2 — SIL Open Font License 1.1 */',
    '',
    `export const FONT_BASE64 =`,
    `  "${b64}";`,
    '',
  ].join('\n');
  await Bun.write(FONT_DATA, header);
  return bytes.length;
}

// ── 2. Bundle ───────────────────────────────────────────────────────

async function bundle(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [ENTRY],
    target: 'browser',
    format: 'iife',
    minify: true,
    sourcemap: 'none',
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('the bundler failed');
  }
  const output = result.outputs[0];
  if (!output) throw new Error('the bundler returned nothing');
  return output.text();
}

// ── 3. Injection ───────────────────────────────────────────────────

/**
 * Inline scripts cannot contain the sequence `</script>`, not even
 * inside a string. It would silently break the HTML.
 */
function guardInlineScript(js: string): string {
  return js.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
}

// ── 4. Verify that it is truly offline ───────────────────────────────

/**
 * Only `rel` values that trigger a download matter. `canonical`, `alternate`
 * and `author` are pure metadata: they point to a URL, but the browser does
 * not request anything, so they don't break the offline promise.
 */
const LOADING_LINK_RELS = ['stylesheet', 'preload', 'prefetch', 'modulepreload', 'icon', 'apple-touch-icon', 'manifest'];

const REMOTE_LOADERS: Array<{ pattern: RegExp; what: string }> = [
  { pattern: /<script[^>]+\bsrc\s*=\s*["']https?:/i, what: 'a <script> with a remote src' },
  { pattern: /@import\s+(?:url\()?["']?https?:/i, what: 'a remote @import' },
  { pattern: /url\(\s*["']?https?:/i, what: 'a remote url() in CSS' },
  { pattern: /\bfetch\(\s*["'`]https?:/i, what: 'a fetch() to a remote origin' },
  { pattern: /\bimportScripts\(\s*["'`]https?:/i, what: 'a remote importScripts()' },
  { pattern: /<img[^>]+\bsrc\s*=\s*["']https?:/i, what: 'a remote <img>' },
];

/** `<meta>` and `<link rel="canonical">` are metadata, not loads. */
function auditOffline(html: string): void {
  const problems: string[] = [];

  for (const rel of LOADING_LINK_RELS) {
    const pattern = new RegExp(`<link[^>]*\\brel\\s*=\\s*["'][^"']*\\b${rel}\\b[^"']*["'][^>]*>`, 'i');
    const match = pattern.exec(html);
    if (match && /https?:/i.test(match[0])) {
      problems.push(`a <link rel="${rel}"> pointing to a remote resource`);
    }
  }

  for (const { pattern, what } of REMOTE_LOADERS) {
    const match = pattern.exec(html);
    if (match) {
      const at = html.indexOf(match[0]);
      problems.push(`${what} — near: …${html.slice(Math.max(0, at - 60), at + 60).replace(/\s+/g, ' ')}…`);
    }
  }

  if (problems.length > 0) {
    throw new Error(`the HTML loads remote resources:\n  - ${problems.join('\n  - ')}`);
  }
}

// ── Run ──────────────────────────────────────────────────────────────

const fontBytes = await bakeFont();
console.log(`font       ${kb(fontBytes)}  (${kb(Math.round(fontBytes * 4) / 3)} in base64)`);

const js = await bundle();
console.log(`bundle     ${kb(new TextEncoder().encode(js).length)}`);

const css = await Bun.file(STYLES).text();
const template = await Bun.file(TEMPLATE).text();

const html = template
  .replace('/*__STYLES__*/', () => css.trim())
  .replace('/*__BUNDLE__*/', () => guardInlineScript(js));

if (html.includes('/*__STYLES__*/') || html.includes('/*__BUNDLE__*/')) {
  throw new Error('missing markers in the index.html template');
}

auditOffline(html);

const outBytes = new TextEncoder().encode(html).length;

// The same HTML under two filenames:
//   - `placeholder.html`, the familiar name for double-clicking.
//   - `index.html`, the default entry point served by GitHub Pages.
await Bun.write(OUT, html);
await Bun.write(join(OUT_DIR, 'index.html'), html);

console.log(`\n✔ ${OUT}`);
console.log(`✔ ${join(OUT_DIR, 'index.html')}   ← for GitHub Pages`);
console.log(`  ${kb(outBytes)} each, self-contained.`);
console.log('  Double-click either one. No server or internet connection needed.');
console.log('\n  GitHub Pages publishes dist/ automatically on every push to main.');
